### PR TITLE
Updated Puppet version to use 6.x (2019.8 LTS)

### PR DESCRIPTION
**Pull request by greglarkin**

### CODE REVIEW

**Review by awilliamson-puppet — CHANGES_REQUESTED** [review]
This looks like it accidentally added the 'final' state of the lab to the starting state - the orig pe_201_base doesn't have any manifests - presumably because we go on to create them during the 201 day.

**Comment by greglarkin** [comment]
Gah, my script (e.g. me) took a heavy-handed approach to scripting these changes so we can close this one.

**Comment by greglarkin** [comment]
Actually, I have no clue what happened here 🤦‍♂️

**Comment by greglarkin** [comment]
Definitely used the wrong base branch at the very least

**Pull request closed without merging**
